signed int cmdCheck(char str[]);
void saveFunction();
void loadFunction();
void downloadFunction();
void createFunction();
void rmFunction();
void detailsFunction();
void openFunction();
void lsFunction();
void infoFunction();
